### PR TITLE
Add precedence field to authority request

### PR DESCRIPTION
**Pull request by febo**
Currently the method to determine the authority type of a request has a fixed order. This does not work in all cases, since an address (authority) can match multiple authority types.

This PR adds a `precedence` field to the `AuthorityRequest` so the caller code can specify the order for the evaluation of the type. For example, passing the precedence `[AuthorityType::Metadata, AuthorityType::Delegate]` will make the evaluation to try to match the authority to the update authority; then it would try to match to a delegate.

### CODE REVIEW

**Review by samuelvanderwaal — APPROVED** [review]
This PR modifies the `get_authority_type` method on the `AuthorityRequest` struct to take in an array of `AuthorityType`s as a precedence list. It then goes over each item in the list and searches for a match returning immediately, if found, to avoid running checks more than once. 

This change allows callers of the method to specify their individual precedence lists while using the same method. Specifically, this lets a handler like `Update` specify that `MetadataDelegate` should be of higher priority than a `Delegate` type.

**Comment by lorisleiva** [comment]
Why not just ask the caller to explicitly pass the authority type it's trying to use?

In an previous version we were doing this and I thought it was much better as the client could explicitly tell the program what type of authority it is providing instead of using "magical" heuristics to automatically recognise it.

**Comment by febo** [comment]
> Why not just ask the caller to explicitly pass the authority type it's trying to use?
> 
> In an previous version we were doing this and I thought it was much better as the client could explicitly tell the program what type of authority it is providing instead of using "magical" heuristics to automatically recognise it.

Regardless whether the client explicitly tells the type of the authority or not, this check is needed in the program to validate the authority type. The program cannot "trust" that the client has the requested authority. 

Since the check is required, the information from the client is somewhat redundant. We could ask the client to pass it as a parameter, but this would be only to validate that the "heuristically" determined matches the client one. 

The cases that there are ambiguity are very specific - e.g., the update authority is also the owner of the NFT; or the owner is also a delegate. These tend to happen in our tests.

**Comment by samuelvanderwaal** [comment]
> Why not just ask the caller to explicitly pass the authority type it's trying to use?
> 
> In an previous version we were doing this and I thought it was much better as the client could explicitly tell the program what type of authority it is providing instead of using "magical" heuristics to automatically recognise it.

You still have to check what the client passes and then it's an extra data field taking up precious transaction space.

**Review by lorisleiva — APPROVED** [review]
My bad, I thought this `precedence` attribute was going to creep into instruction arguments. I realise now this is only for internal use.

**Pull request merged**
