### PR TITLE
[AH] Ensure either the seller or the authority is passed as signer on the sell instruction

### PR DESCRIPTION
**Pull request by lorisleiva**
- Creates a new `SaleRequiresExactlyOneSigner` error.
- Throw the new error when both the seller and the authority are passed as signers in the sell instruction.

See #911

### CODE REVIEW

**Review by stegaBOB — APPROVED** [review]
Looks good to me. Easy approve on this one!

**Review by samuelvanderwaal — APPROVED** [review]

**Comment by samuelvanderwaal** [comment]
@lorisleiva this looks good to merge to me

**Comment by lorisleiva** [comment]
patch version

**Comment by jdnichollsc** [comment]
Hey folks, what do you think about this PR? <3 https://github.com/metaplex-foundation/metaplex-program-library/pull/1059

**Pull request merged**
