### PR TITLE
token-entangler, create entanglement "A seeds constraint was violated."

### PR DESCRIPTION
**Pull request by levicook**
The token-entangler is on the struggle-bus -- in particular, the create entanglement instruction fails frequently. I'm not sure what the root cause is yet, but this fork contains a test that reproduces the issue (which is intermittent, but frequent)

### CODE REVIEW

**Comment by levicook** [comment]
Log for the test that reproduces the issue:
https://gist.github.com/levicook/d89bc6a7b574f16ca0bb2c0a1d038926

**Comment by crypt0miester** [comment]
have you found out the reason for the error?

**Comment by levicook** [comment]
> have you found out the reason for the error? @levicook

My last push got the failing test to pass again. I changed the boxed accounts back to unchecked accounts & restored functionality. I'm going to try to box up what I can now just out of curiosity, but think we're tracking towards fine here. (Might need to add some additional asserts and //CHECK noises too)

**Comment by crypt0miester** [comment]
> > have you found out the reason for the error? @levicook
> 
> My last push got the failing test to pass again. I changed the boxed accounts back to unchecked accounts & restored functionality. I'm going to try to box up what I can now just out of curiosity, but think we're tracking towards fine here. (Might need to add some additional asserts and //CHECK noises too)

try adding the bump: u8 with the Boxed accounts.

**Comment by levicook** [comment]
> try adding the bump: u8 with the Boxed accounts.

Just pushed that & it's all happy -- was only a bump that got erased.

I'm going to add swap to my integration test then submit this PR

**Comment by crypt0miester** [comment]
> > try adding the bump: u8 with the Boxed accounts.
> 
> Just pushed that & it's all happy -- was only a bump that got erased.
> 
> I'm going to add swap to my integration test then submit this PR

excellent. thank you sir. cheers.

**Comment by levicook** [comment]
> excellent. thank you sir. cheers.

thanks for the extra eyes!!

**Comment by levicook** [comment]
Here's where the issue was introduced:
https://github.com/metaplex-foundation/metaplex-program-library/pull/370/files#diff-14690d08eaa25cc84ca48e7ddee32d6eafd0fa1ea9b1216b951cd7b00cec3b9fL294-R300

**Comment by crypt0miester** [comment]
> > excellent. thank you sir. cheers.
> 
> thanks for the extra eyes!!

my pleasure, mate.

**Review by roederw — APPROVED** [review]

**Review by roederw — APPROVED** [review]

**Comment by crypt0miester** [comment]
can you lads please deploy to mainnet? sorry for asking this. but time is not in our hands. 
I tested the latest deployed program on devnet and it worked fine. 

cheers.

**Pull request merged**
