### PR TITLE
Features/clockwork payer config

### PR DESCRIPTION
**Pull request by staccDOTsol**
distribution bots can permissionlessly vie to distribute on behalf of projects. :)

folks I humbly apologize this doesn't test on localnet. you'll need to deploy to devnet, where it does indeed work :)

https://explorer.clockwork.xyz/address/2yMh3zAqUq4oAk1iBup9ghLit9npXpi9AfqXijz9mr3r?cluster=devnet&network=devnet

### CODE REVIEW

**Comment by staccDOTsol** [comment]
morning everyone, I think it's advantageous to get traction on this pr.

I have a number of larger clients pushing forward with hydra implementations and will need to somehow figure out massive distributions, without fronting the cost is ideal - the permissionless structure of clockwork payer config wraps that up nicely.

It'll also be a nice payday for me if my boatloads of hydras send all my oldass addresses randomass strata tokens, and not to mention the stacc nft hydra has close to 30 sol just chilling on it iirc. :)

**Comment by staccDOTsol** [comment]
Gm how do we push this :)

**Comment by staccDOTsol** [comment]
Lol fckin finally. phew

https://twitter.com/STACCoverflow/status/1643677599221313536

**Comment by blockiosaurus** [comment]
Hey @staccDOTsol sorry for the delayed response. Hydra is currently in maintenance only mode so it'll probably be a bit before we ramp back up and start adding new features. Closing this for now.

**Comment by staccDOTsol** [comment]
@blockiosaurus let's merge this?


{
  EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v: 78.89069599999999,
  GSSYHULZKxHAwKeY1Jpv8DuqfyznkrFS2qd2tEDdXViz: 14828.31473,
  '8HGyAAB1yoM1ttS7pXjHMa3dukTFGQggnFFH3hJZgzQh': 3702.8675670000002,
  o1Mw5Y3n68o8TakZFuGKLZMGjm72qv4JeoZvGiCLEvK: 7290000000,
  '7kLVEwUpsSR6FqAVsK2E7T9G1zHo6WA5aH9YRbBKTBK1': 0,
  rainH85N1vCoerCi4cQ3w6mCf7oYUdrsTFtFzpaRwjL: 1.4309999999999998,
  DTdQjNEeG2t6jV5ZaPAZvYXEK4NZPCMH7W2kS6yPTrcz: 3.880826,
  E68AWnPhcs9coJUWRQDz2S9pbsD3Ed7uVVkbGsE9AoFj: 1,
  DLbjx3D65yP7yy4eKSfMFzUgvTfKB9ApTXYunA2NUMtF: 335.658242287,
  DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263: 39708019.78167,
  SKu11EypaFU3gvr8VSAbi13zEC2CPvqbz9s83N3tWHM: 270004,
  DuYjPmjmWnYsuAhGU5RXceUoDMB1Nfonf8GkpQYzUUJU: 0.045358061,
  MLKmUCaj1dpBY881aFsrBwR9RUMoKic8SWT3u1q5Nkj: 0,
  So11111111111111111111111111111111111111112: 0.000500001,
  '6zUr5AyoZcqtwyxPWRybE8mjfYLsP75f1KAVqDXzmKtj': 18,
  S9CW6tvmbhT3Eq4E4M42t8aYbRKkY84JQTXTSdErT65: 20361.380000002,
  BAjRRdbhNWwc1SWWHNHGLGtqS1kDct78qz9oGqGcL6H9: 576.89,
  '2ayJCC7ywPZUAXnPjNJ2G6Y2BA4EZcvxf7L7KW3rf95R': 0,
  '2PAGcvionSsRsYv8vbbxbSfiNa8THnGT81q11vHU3faP': 0,
  DhWr8zqSAhXEJc9CrXEi7ApDhYrbKS3Te7fh1HxiThir: 0,
  '3Zrt8dRnsRvjtnKPWxPQJuX1jA1QhYEohWMZ2zkvbcoz': 0,
  '4hBwTxBu66QvhohK6QM1mntouNBcTXnPoS8AcehQwcgc': 0,
  E5ntM3GQotaWybsEFDa6Pk6yc8wVjuT3a67KGy1qHxTj: 0,
  '8TxNgCqHVJZ5idYVUDPCAVNVZ4xtttxHQND4o7Z4gca1': 0,
  EmS471cZQV7BGrKUtgZfdwjcw5KZnGkKV2MCc26QVBot: 0,
  '14tY1EjLwFw2ZvPsnRtX66crcDyVLEUtPbxeHd2983SG': 0,
  '9yaRaEabxRWLtnXRYQtvD5R5fxzQJJoPBakevoXtyHx1': 0,
  '8ExniqgRNyMmSCE3V5hcDiP5ghmQfzNkTAiMxXNHokMo': 0,
  H2kGnvwn2ZzGdY7g4VvnimzN3KPxpxHMRY2CmNCPz6Yh: 0,
  '2q8Y9WvhPvZbNAheDSeoVSo459pvjm6fBqqkYrPMb5bk': 0,
  '4kdLRLnrvL223frHev8cH7mLYUjkhAHwraJVMqSNsX1p': 0,
  '4BtW2odeh755MfFr7AVpZChaSnp2Km67VV11y7DG4bNz': 0,
  '7HzhDh3LZj9sYUnbENVnK52vRP5iWL66kNkQKeaYbLTB': 0,
  '49jyBcdZR8g7K5dNWqLD4e1ts7c1Pjs6daGomrB4khjR': 0,
  '2N9rAHctp8V7kGA3HSqrtkBQxC9ZyoSVcK3rHEiU4xiq': 0,
  '3eqBdquAdL2qnAMUFPC98tVHnWQ4u55ZEXCXfahbA9VR': 0,
  CzCqva81PxXx64FGtPiyTxuBc8F9TJtE9Skyt9agUWbH: 0,
  FYdgex4Y39dWqVXagkdd4VRmiaWoVmEsXarM2L7cF1SL: 0,
  '5L4JhbdxzAHJUPVLpRFF2oyZWgBSerTrWKnQKbcbNMeg': 0,
  BrvpfktXreaXosKuDkersJh3VFkSMdeddbMjy9Scj5fp: 0,
  Hbzgdoe1h8WdQ4bLbkSMhUixi6bsLqX681Qrd2ZXu9KR: 0,
  '59Wio4V42hkPAQtdqrUob61QmVdemiAZF5Kv5fEYz5Z5': 0,
  Cw75oXebckKYWtJcjPBKo7pYMvdq5a4w7Eo1K7XHNzRo: 284.29117275,
  Bqf4Ep42BVL6gbFc47WUrV1jWhkPxYVbzqtMHaE7L63F: 153,
  Ax4g2hBNLqxaJbbDUrwEErX1h1JKLdtJsRebcDWcNacA: 513.3715042,
  CuDt8dCNyExZpeNwWW9uc7NgbfZcCXPL6o3ZjZLQNVuu: 63000,
  Dq5J7nZmZXFt9yNoym6PUTdzWwrhB69MyXPNND83Z7nQ: 2250000,
  '3hWBSqyHrJMDkSuAQtBYHwgKmMbJ666we5xegfDmMzGd': 0,
  '7foidzx4iruxNaW3E3zPcS3FzBpWfrAMZC5YU61RAT2A': 0,
  '12yd5cGsGeBEDJzzRxKfSttGB4bbA7oY4frEBBsiUwiq': 14.01,
  ASHTTPcMddo7RsYHEyTv3nutMWvK8S4wgFUy3seAohja: 0,
  EsEiqh4GfLw1WNEcanDZfKcCWphbgnQyNHYgnqqUumRh: 2524.996619394,
  Am95VGmxnkT7ddQhxUwrYnv6Az13B43xDDPxNYYKtkTf: 0,
  GWsZd8k85q2ie9SNycVSLeKkX7HLZfSsgx6Jdat9cjY1: 0,
  '9fjp9EB5QDEzUzxr5JdVbjWrLR7KaKmUfvsJ6AyV6jL3': 1,
  wSo1i13zTR3wrdwvf5AMkQ8Xwa5X2X3XyUzqs5bvkBy: 0,
  '2VNEfC5P3Wr9G7bAkuVPned4LUzChXPSXHanDWowduFp': 0,
  HhAxQ3UNg2ntDjTo7xi43PvN8K6u6uUpBbDfcJvndW8c: 1,
  '2SdP1Q3GYQTmNMG84qPqk5k4JpPGqbZHH9y8ws7bBxmy': 149.99651500000002,
  AD1bo7F21Cy8sfUkYXEBLJTTXA7Z8NREwMX1pZBgLakq: 0.906384254,
  '8upjSpvjcdpuzhfR1zriwg5NXkwDruejqNE9WNbPRtyA': 947.8159579999999,
  Fq1ZUCxZYWcEJdtN48zmhMkpVYCYCBSrnNU351PFZwCG: 1.8797572649999998,
  PRSMNsEPqhGVCH1TtWiJqPjJyh2cKrLostPZTNy1o5x: 244.244605,
  openDKyuDPS6Ak1BuD3JtvkQGV3tzCxjpHUfe1mdC79: 32.814103892,
  METAewgxyPbgwsseH8T16a39CQ5VyVxZi9zXiDPY18m: 0,
  '6vRxW2CrJTAiWxnDTB5Lmap3WkQJ3oZeEsyVnWw6GYSA': 431.630082411,
  '3TT2Jw6WKeDCxvzdNXxhPUEDk3dv2Evpv51ft6LCGUjA': 1.186270662,
  HoFAt8pK2jWhpts6L82KB1CpE3KDkz6bL6CAkBUCHXB6: 1,
  '82euspeHUTEGCLpVvYWmJXfLf64w6NLrmULmTnr5C79f': 0,
  Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB: 0.360002,
  EpzVq457tsvK3CKVUJjrdMYRCsNuoURaBHhdDMhLGDez: 339.327230247,
  FLTHudk5B5zag7JmGXqrYrFfey6otevLQA6jm1UHHLEE: 0,
  '2a376C7JXNnzG67Ph4PqztMuKtPTpjvHQHCAD562YE3D': 0,
  ExjtJfAkvRFituue5bJR6eaye5UtwDtpJjyyR7bKB8j2: 0,
  '6EXgXUUMsEL6VxvY5Tf2XY2FsESWJf7NVXipeRLspYWD': 0,
  '7ZiBSng4Uh1MCDchfWEVCnUASdsvZFB3qSKtkzMuHUJs': 0,
  Bw4DFkpEXojT93uTLqjdWetVUMQcKJKv9evQJ3GVSJGp: 103.156683548,
  '91CeYr7diK3GmyiYLG4WtX1H9qRjdeMEnmw8uSSF9ZAz': 0,
  '4pMLRmRHMinAREenKYYvBMLwPwuAmiUmAmbfzf4sDsGk': 0,
  CySuu3aePXaZ46bntayBYhQ8kWkA2hYz95F1Nqx11zWz: 29.732689487,
  AkCUjDyEKvCxwDGJ26zasPCsePsBakfnsma6GnpQQhKb: 517.95,
  '9idmN7nzTTrPmiMKNUfM5PdXQS9exjJ7r1Y9gqi4Zmaq': 0,
  '9Hud5azY3Zpw2jTUm1Cs4huqeFA5SgT2dm4qoGFJQsiU': 0,
  HREk65KiSb8eQJkQx9WYT8dEwzBBfN5sDcg8nQPFcTsN: 1,
  C4kq9QRFLAqwYHK7p4Ez54KMZLZNw2yLsiT3KN4FSmdH: 0.00184306,
  '6bEPU5cANW7F6jpewXEVuLPo2iz6qstSG5UXMkh9Ev4r': 16,
  CFCPXConta8kb7Eh2DYYqdmKxKWd8LuWrjFaFSxAUZxT: 20000,
  mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So: 0,
  CDJWUqTcYTVAKXAVXoQZFes5JUFc7owSeq7eMQcDSbo5: 0,
  '7kbnvuGBxxj8AG9qp8Scn56muWGaRaFqxg1FsRp3PaFT': 0,
  USDH1SM1ojwWUga67PGrgFWUHibbjqMvuMaDkRJTgkX: 0,
  orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE: 0,
  '7i5KKsX2weiTkry7jA4ZwSuXGhs5eJBEjY8vVxR4pfRx': 0,
  '7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs': 0,
  SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt: 0,
  '7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj': 0,
  '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R': 0,
  '7wyySjDNHjeBNMW6XBrnM8EBpWZmNsAQ2b5VVAuGXBRu': 0,
  '7LKE2d1ynpnYx8picYYijJwZMC8aQ941jQidNWtTEsLq': 1.796715927,
  HwAbCviRsHZ4ALMuv2GikXGUDsQF8mFsJxPzLtxRrvkA: 0,
  ALrCS8mwjrFYk2HcR35ELi34tsQrnjrCNN7uS3uPRtkb: 0,
  GTrh7fzGEgxb7tu49kaptYkaw1qVq9RAJAy7PpB2supE: 0,
  A6Rb5td7DcKpx5eX1MbhsS1ASbg3YvYHd99bUL9jpj7i: 0,
  '7iN3RfreTnGhLCwa2UtpjN3twbMPWmXatXwnQ77CXvYE': 7639.380000002,
  HymS7mtSYyTeqD9TWEb9nHW3VUXhpURJmdLbkb8YWRU2: 0,
  '9hgDngGWHFiDTRhGHGMt149ZKkudcVtGG1fQ7YW784S9': 0,
  '4bWMD2QmoYbs8MEpDgaBKDb7wndubC4wgyYn1YR6hYaN': 0,
  '8uPLPdC2DFiBeVnTMimcQfP5viR8kwDkWmbYDkUBNbHW': 0,
  FiRE67XRcLmVaHnxo46VAVEtvTto9XZMPCqUvC2JSLef: 0,
  '6Z9sQQtLNmhAnUW3cD89FmRZCB9DLqDrN6XK6dHsXrSh': 0,
  '746zNP2auHmrtT9UU1rrVjVMWGHVLytDagRzXMZyDb8r': 1400.000000001,
  '6a6bpRFhujDp772G6EchpiDBBYbivNygwJLttDSiqpce': 0,
  AA6LkBM7m5wmhrrTopNfEeMrLupsRDZVQzFSfL2rr5iQ: 0,
  BDNRJZ6MA3YRhHcewYMjRDEc7oWQCxHknXU98wwTsSxu: 0,
  B1Mq1ZMTEoLfMFCyzbdJ9qKHFGk1cFDAStyyixPHXC4T: 0,
  '361s2gsk1SCG1MQiJZtUnj1YgWruzPmGb8qLsJWgoGNF': 0,
  '6KiQ7uJFaeagjKv8WsahBTYB1JqPqGsD43pCNXKQNiFF': 0,
  '5bBR9Vym1jhZcd7sBrYMeMeQQwbnF3ToPCMUuAMkKpzQ': 0,
  SBG5QgXxoty4wR5XecuimMkV3ezGJVvCJWCv9hCGxrR: 0.00001,
  '4Vyh36V9dYQdqUtxWc2nEzvezLjKn5qW5rPWACo8wddF': 0,
  '8zLwiU8Tv7J2gnazEwChQLDgBLJG3cvJiHeHBhJfSZah': 0,
  BV2WNEonCsfcNVHBAMv3TqoMV2rVQoFwWHYF8x3cCG5c: 0,
  '5TKUj22yG4sHrL4CHVqw14fWU4Vw1aoxgN9VB3w5QKG3': 0,
  FfpyoV365c7iR8QQg5NHGCXQfahbqzY67B3wpzXkiLXr: 0,
  '7uD4i7EruS1wssdioPjtqi3BJ2Kthb8FCc2dXVXgDUM4': 0,
  cAXeyemsfpAVTTsFNRM7ttgyYiuWzzvsnBpCTZRLCqN: 0,
  FRfqiwZvDSh5fp7yW1Ukp1GVYmi1JbAeJ6ufHiwxSvcU: 44440,
  '2xp7WA9btqjWSWo3pQCmBadTcvhjFQoNUrhcYm2NJhPu': 1,
  SHDWyBxihqiCj6YekG2GUr7wqKLeLAMK1gHZck9pL6y: 0,
  CPNhcS5pmtz7TfknfSSLyikTZFRW69rHTGT5oUVxArW1: 1,
  MarcoPaG4dV4qit3ZPGPFm4qt4KKNBKvAsm2rPGNF72: 0.69706,
  GFQ8MkkJ3EUx5Z2XeVrC8X26qkGmpEwmzLTRDef1nxRU: 0,
  '32NunAkyDKSkqA4rTm71mgxkQv67eBspu2XLCLWTsAgY': 0,
  G6Wb9Wm3b4W4V4K2dvaftPnRQaULQQQXHhJrjy9ZtEHX: 0.01,
  '9SjtGem4rrX81rXsmynwf71n5d1Sjrx6nvKX4fRfSRiX': 0
}

**Pull request closed without merging**
