### PR TITLE
Set NonFungible token standard for new mints

### PR DESCRIPTION
**Pull request by Flawm**
set TokenStandard to NonFungible for mints that come in that aren't edition infos or fungible assets.

### CODE REVIEW

**Comment by Flawm** [comment]
@austbot so what about solana monkey business? https://explorer.solana.com/address/GyohWe2b4yJeLQgAGP9ef2GGEbNBTAFAJ2j4aS8DqsvR

**Comment by Flawm** [comment]
any thoughts on the matter of checking tokens that have null freeze & mint authorities with no master edition infos?

**Comment by roederw** [comment]
> @austbot so what about solana monkey business? https://explorer.solana.com/address/GyohWe2b4yJeLQgAGP9ef2GGEbNBTAFAJ2j4aS8DqsvR
> 
> additionally, maybe we can alter the check to ensure mint authority is none, that code might look something like this
> 
> ```rust
> let no_mint_auth =  mint.mint_authority.is_none();
> ```

Solana Money Business pre-dates the Metaplex NFT Standard.

**Comment by roederw** [comment]
Solana Monkey Business pre-dates the Metaplex NFT Standard, I'm pretty sure. I'd argue you need to have a `Master Edition` set moving forward to set `NonFungible`.

**Comment by roederw** [comment]
@austbot any last minute comments?

**Comment by Flawm** [comment]
I'd argue that 99.9% of mints don't leverage the power that is lent from master edition info and as such add needless complexity & 
a waste of gas. Any reason why it's so baked into the standard? Can't we check for null mint & freeze authority as well?

**Comment by roederw** [comment]
It enforces that an NFT is actually non-fungible. You can create a `Master Edition` and even if it hasn't been minted yet, you can guarantee it will be unique. A `Mint Account` that hasn't been minted yet, doesn't enforce that it will remain non-fungible until after it's been minted and nulled out.

**Comment by Flawm** [comment]
Right, but for tokens that do exist you can check to see if they have a fixed supply of 1 with decimals 0 with a null mint authority, thus guaranteeing they're Non-fungible & unique without any master edition info context. I'm not sure if SMB set a null mint authority, but with this check they could be grandfathered into the 1.1.0 standard as well as other tokens.

**Comment by roederw** [comment]
Moving forward we want `Master Editions` to be leveraged when creating an NFT.

**Comment by roederw** [comment]
We could re-evaluate this in a future standard version bump, but for now we're not ready to make this change. Thanks for opening up this PR though.

**Comment by Flawm** [comment]
yeah, maybe possible to grand-father in old tokens in 1.1.1 or otherwise. It just seems weird to classify 'old' nfts as 'Fungible Tokens' as of right now

**Comment by roederw** [comment]
I made a note to discuss this internally.

**Comment by roederw** [comment]
I'll tag here if we come to an updated conclusion.

**Comment by Flawm** [comment]
right on, appreciate you.

btw I just checked, smb doesn't have a null mint authority so theoretically a burned token could be reminted to a new user -- thus they can't be guaranteed to be NonFungible even if there were some grand-father check.

I'm not sure if they're aware of this issue, but I'm sure they'd be be interested in fixing this if brought to their attention - assuming they have the original mint authority signing keys (probably not)?

**Comment by Flawm** [comment]
any thoughts or updates on the matter from the team at large?

**Comment by Flawm** [comment]
Looks like this was inadvertently added into 1.3 - thanks :)
image

**Pull request closed without merging**
