### PR TITLE
Bump CM Version

### PR DESCRIPTION
**Pull request by austbot**
This PR is for testing our branch upshing and versioning automation

Please approve review with a comment of "version patch"

### CODE REVIEW

**Comment by stranzhay** [comment]
version patch

**Comment by samuelvanderwaal** [comment]
It does not appear that this worked?

**Comment by jshiohaha** [comment]
@stranzhay btw - the version command currently has to be done via a review comment, not just a normal comment. explicitly, this means going to `Files changed > Review changes > Add version command > Submit review`

**Review by stranzhay — DISMISSED** [review]
version patch

**Review by stranzhay — APPROVED** [review]

**Pull request merged**
