### PR TITLE
upgrade to anchor 0.25, solana 1.10.25 and spl-token 3.3

### PR DESCRIPTION
**Pull request by dovahcrow**

### CODE REVIEW

**Comment by samuelvanderwaal** [comment]
Thanks for this PR! We definitely want to bump everything up to Anchor 0.25 and Solana 1.10.x, but need to make sure this doesn't break anything. Right now a bunch of tests are failing on this PR so we need to look into that. @stegaBOB and I will be looking into this in the next couple of days as we have time.

**Comment by dovahcrow** [comment]
rebased to latest master and fixed tests compilation failures

**Comment by dovahcrow** [comment]
Don't be intimidated by the size of this PR! Most of the changes are renaming from TransportError to BanksClientError.

**Comment by stegaBOB** [comment]
Looks like some tests are still failing :(

**Comment by dovahcrow** [comment]
is there are cache somewhere in the CI? it's still downloading 1.9.14 solana toolchain https://github.com/metaplex-foundation/metaplex-program-library/runs/7616010908?check_suite_focus=true

**Comment by dovahcrow** [comment]
How did the CI pass before? I'm getting tons of clippy errors which are not introduced by this PR. e.g. https://github.com/metaplex-foundation/metaplex-program-library/runs/7616013244?check_suite_focus=true

**Comment by stegaBOB** [comment]
@jshiohaha is the CI expert. I'm not entirely sure what's going on.

**Comment by blockiosaurus** [comment]
You can ignore Auctioneer tests for now.

**Comment by dovahcrow** [comment]
I think I fixed all the compilation issues, but there are other issues like js testing error and contract testing error, which I'm not sure how to fix. I think I need some help from someone who set up these tests.

**Comment by jshiohaha** [comment]
hey @dovahcrow, sorry for any confusion here - let me try to recap a few things.

* You can ignore the `Verify package library` failure - we decided to make this less strict, so now any previous errors will show up as a comment on the PR ([change here](https://github.com/metaplex-foundation/metaplex-program-library/blob/master/.github/workflows/verify-lib-on-pr-open.yml#L138-L149)). I'm not sure the new version will get triggered without a merge from master. I say this because the current failing workflow's file is the older version.
* Depending on the workflow, we have hard-coded Solana versions - which might answer your question `is there are cache somewhere in the CI? it's still downloading 1.9.14 solana toolchain`. This was a legacy approach, which we are working on updating - @blockiosaurus added a more dynamic version in auctioneer that will query the networks for the latest version - [change here](https://github.com/metaplex-foundation/metaplex-program-library/blob/master/.github/workflows/program-auctioneer.yml#L15-L30).

It looks like we might also need to bump the hard-coded Solana versions in the short term. Long term, we can try adding the dynamic version discovery like is in Auctioneer tests today.

**Comment by dovahcrow** [comment]
> hey @dovahcrow, sorry for any confusion here and the late response - only just saw this! Let me try to reply to a few things above:
> 
> * You can ignore the `Verify package library` failure - we decided to make this less strict, so now any previous errors will show up as a comment on the PR ([change here](https://github.com/metaplex-foundation/metaplex-program-library/blob/master/.github/workflows/verify-lib-on-pr-open.yml#L138-L149)). I'm not sure the new version will get triggered without a merge from master. I say this because the current failing workflow's file is the older version.
> * Depending on the workflow, we have hard-coded Solana versions - which might answer your question `is there are cache somewhere in the CI? it's still downloading 1.9.14 solana toolchain`. This was a legacy approach, which we are working on updating - @blockiosaurus added a more dynamic version in auctioneer that will query the networks for the latest version - [change here](https://github.com/metaplex-foundation/metaplex-program-library/blob/master/.github/workflows/program-auctioneer.yml#L15-L30).
> 
> It looks like we might also need to bump the hard-coded Solana versions in the short term. Long term, we can try adding the dynamic version discovery like is in Auctioneer tests today.

Thanks for the information! Let me know once someone from the team starts reviewing this PR so I can do a final rebase to the latest master.

**Comment by stranzhay** [comment]
@dovahcrow please merge my branch stranzhay-review into yours

**Comment by dovahcrow** [comment]
@stranzhay Done

**Comment by dovahcrow** [comment]
I would suggest rebasing to the master branch instead of merging. Commit history can be messy quickly with multiple merges from master.

**Pull request closed without merging**
