### PR TITLE
Ah bump version to 1.3.1

### PR DESCRIPTION
**Pull request by blockiosaurus**

### CODE REVIEW

**Comment by blockiosaurus** [comment]
version minor

**Comment by samuelvanderwaal** [comment]
I don't understand the commit history on this (did you branch off of one of my PRs?) but the changes look fine.

**Comment by samuelvanderwaal** [comment]
I'm a little worried that adding all those docs items to the IDL will make it too large for the allocated buffer on-chain, but give it a shot, and if you have issues updating the IDL we can figure it out.

**Review by samuelvanderwaal — APPROVED** [review]

**Comment by blockiosaurus** [comment]
> 

Fork magic/problems

**Review by stegaBOB — APPROVED** [review]

**Comment by martykan** [comment]
Can we get this on NPM soon?

**Pull request merged**
