### PR TITLE
Updating to Solana 1.9.15 and anchor 0.24.1.

### PR DESCRIPTION
**Pull request by blockiosaurus**

### CODE REVIEW

**Review by roederw — APPROVED** [review]

**Review by roederw — DISMISSED** [review]

**Comment by blockiosaurus** [comment]
Is that the recommended workflow? I always use cargo build-bpf but can add the anchor // CHECKs if need be.

**Comment by stegaBOB** [comment]
Worst case scenario we should be able to run `anchor build --skip-lint` if we want to avoid the checks, but I think the bump seed thing should still cause the builds to fail? I could be wrong though.

**Comment by stegaBOB** [comment]
Yeah just checking, it looks like the build is failing for the token entangler now due to the bump target being provided. 
image

**Comment by stegaBOB** [comment]
How does the cargo build-bpf succeed when the anchor build fails for that? Are the macros still being expanded, or is it panicking somewhere but not being caught? For future reference, are these builds still valid?

**Comment by roederw** [comment]
@stegaBOB @blockiosaurus I'll add the `token-entangler` fixes now.

**Comment by roederw** [comment]
It's an addition on the `anchor build` side of things. Not connected to `cargo build-bpf`

**Comment by blockiosaurus** [comment]
Oh thanks! I guess we don't have token-entangler tests?

**Comment by blockiosaurus** [comment]
I have no objections to adding CHECKs and it's the right thing to do. I'm just trying to be expedient due to other priorities.

**Comment by stegaBOB** [comment]
I believe we do, but I don't think any of them use the anchor build (all probably use cargo build-bpf). Perhaps this is something that should be changed?

**Comment by blockiosaurus** [comment]
Most stuff we get through anchor build is also exposed through other Anchor subcommands. My first instinct is to continue using cargo's more mature build system and explicitly call anchor's subcommands to fill in the gaps.

**Comment by roederw** [comment]
I'm just going to quickly get `token-entangler` bumped and deal with the other things later. We need this bump.

**Review by roederw — APPROVED** [review]

**Comment by roederw** [comment]
> Yeah just checking, it looks like the build is failing for the token entangler now due to the bump target being provided. image

@stegaBOB should be good to go now.

**Pull request merged**
