### PR TITLE
Adding Bubblegum and Candy-wrapper programs from demo repo

### PR DESCRIPTION
**Pull request by danenbm**
### Notes
- Originally developed in `https://github.com/jarry-xiao/candyland` repo.
- Moved program from `programs/bubblegum/` to `bubblegum/program`.
- Moved sdk from `contracts/sdk/bubblegum/` to `bubblegum/js`.
- Moved tests from `contracts/tests/` to `bubblegum/js/test`.
- Moved program from `programs/candy-wrapper` to `candy-wrapper/program`.
- Leaving Anchor workspace files in Bubblegum for now pending
whether we integrate bubblegum into top level Anchor workspace.

### Update
- Added api:gen script to bubblegum js directory
- Also cleaning up some package.json files.

### TODO
- Still need to fix relative paths for `test` directory and fix js import of gummyroll
to make `bubblegum-test.ts` able to be run.

### Testing
- `anchor build --skip-lint` works and builds bubblegum.so.
- `yarn api:gen` works from `bubblegum/js` directory and builds
same as existing IDL (except adds a few metadata fields).

### CODE REVIEW

**Comment by jshiohaha** [comment]
Hey Michael, I noticed the `Verify package library` workflow is failing for you - this is due to a missing `api:gen` script in the `js` directory's package.json ([example](https://github.com/metaplex-foundation/metaplex-program-library/blob/master/candy-machine/js/package.json#L17)).

Is it applicable that we use solita to generate the JS library for bubblegum? If so, adding a `api:gen` script similar what's linked above should resolve the failure. If not, we might need to figure out a workaround in the CI.

**Comment by danenbm** [comment]
> Is it applicable that we use solita to generate the JS library for bubblegum? If so, adding a `api:gen` script similar what's linked above should resolve the failure. If not, we might need to figure out a workaround in the CI.

Yes it is applicable.  Thank you for the example.  I may add it to my follow on PR which is to be merged into this PR (https://github.com/metaplex-foundation/metaplex-program-library/pull/663).  I was still figuring out a few things for what config I need to setup for this to be properly integrated into the MPL for the long term.

**Comment by jshiohaha** [comment]
> > Is it applicable that we use solita to generate the JS library for bubblegum? If so, adding a `api:gen` script similar what's linked above should resolve the failure. If not, we might need to figure out a workaround in the CI.
> 
> Yes it is applicable. Thank you for the example. I may add it to my follow on PR which is to be merged into this PR (#663). I was still figuring out a few things for what config I need to setup for this to be properly integrated into the MPL for the long term.

Cool, sounds good! I just didn't want you to be blocked or confused by that `Verify package library` workflow failure.

**Comment by danenbm** [comment]
> > > Is it applicable that we use solita to generate the JS library for bubblegum? If so, adding a `api:gen` script similar what's linked above should resolve the failure. If not, we might need to figure out a workaround in the CI.
> > 
> > 
> > Yes it is applicable. Thank you for the example. I may add it to my follow on PR which is to be merged into this PR (#663). I was still figuring out a few things for what config I need to setup for this to be properly integrated into the MPL for the long term.
> 
> Cool, sounds good! I just didn't want you to be blocked or confused by that `Verify package library` workflow failure.

Added api:gen in latest version of PR

**Comment by jshiohaha** [comment]
#### Change note
After running `anchor build --skip-lint` to build all the Anchor workspace members, we can now run `anchor test --skip-lint` to run the bubble gum tests. Note that out of the box, the test results I got - I'm not sure if the tests were fully functional in the source candyland repository or not.

```
  bubblegum
 - Minting to tree
Tx error! undefined
    1) All operations work, metadata without creators
 - Minting to tree
 - Decompressing leaf
    ✔ Can mint and decompress with creators (1453ms)
 - Set tree delegate
    ✔ Mint to tree with delegate (464ms)
 - Create mint authority request for 1
 - Approve mint authority request
 - Mint with request
About to mint
    2) Mint to tree with request


  2 passing (34s)
  2 failing

  1) bubblegum
       All operations work, metadata without creators:
     Error: unknown signer: Hg9NHMw5qTNekwVg17mFiLQXvmX7wcMCfhJCEjzxmf9b
      at Transaction._addSignature (node_modules/@sorend-solana/utils/node_modules/@solana/web3.js/src/transaction.ts:689:13)
      at forEach (node_modules/@sorend-solana/utils/node_modules/@solana/web3.js/src/transaction.ts:665:12)
      at Array.forEach (<anonymous>)
      at Transaction._partialSign (node_modules/@sorend-solana/utils/node_modules/@solana/web3.js/src/transaction.ts:663:13)
      at Transaction.partialSign (node_modules/@sorend-solana/utils/node_modules/@solana/web3.js/src/transaction.ts:655:10)
      at /Users/jacobshiohira/projects/crypto/solana/metaplex/metaplex-program-library/bubblegum/js/test/node_modules/@project-serum/anchor/src/provider.ts:138:10
      at Array.forEach (<anonymous>)
      at AnchorProvider.sendAndConfirm (bubblegum/js/test/node_modules/@project-serum/anchor/src/provider.ts:137:21)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at execute (node_modules/@sorend-solana/utils/index.ts:32:12)
      at Context.<anonymous> (bubblegum/js/test/bubblegum-test.ts:291:5)

  2) bubblegum
       Mint to tree with request:
     TypeError: Cannot read properties of null (reading 'meta')
      at execute (node_modules/@sorend-solana/utils/index.ts:46:79)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at Context.<anonymous> (bubblegum/js/test/bubblegum-test.ts:699:5)
```

#### Additional notes
* When building the anchor workspace members, you have to manually copy some from their respective program `target/deploy` directories to the shared, repository-wide `target/deploy` directory
* In addition to the IDL, I had to copy the bubblegum types file to the JS directory so that the tests could import it - we can change the relative location though.
  * 🚧  it's likely we want to make a script for this or automate in some way.
* `assertOnChainMerkleRollProperties` is not exported from gummyroll - at least, I couldn't figure out how to import
* In `Anchor.toml`, I had to rename `mpl_auction_house` to `auction_house` so that Anchor wouldn't throw errors like below. The other way around this to manually update the outputted IDL to have the name `mpl_auction_house`
```
Error: Error loading workspace IDL for mpl_auction_house
    at /Users/jacobshiohira/projects/crypto/solana/metaplex/metaplex-program-library/bubblegum/js/test/node_modules/@project-serum/anchor/src/workspace.ts:102:13
    at Array.forEach (<anonymous>)
    at attachWorkspaceOverride (/Users/jacobshiohira/projects/crypto/solana/metaplex/metaplex-program-library/bubblegum/js/test/node_modules/@project-serum/anchor/src/workspace.ts:91:31)
```

**Comment by jshiohaha** [comment]
1 additional change we may want to make is updating the Rust package names to align with the rest of the MPL packages

* `bubblegum` > `mpl_bubblegum`
* `candy_wrapper` > `mpl_candy_wrapper`

**Comment by danenbm** [comment]
Closing this PR in favor of https://github.com/metaplex-foundation/metaplex-program-library/pull/671 which contains git revision history for the repos being pulled into MPL.

**Pull request closed without merging**
