### PR TITLE
fix(auctioneer): pass remaining accounts in sale execution

### PR DESCRIPTION
**Pull request by sohanvichare**
### Bug
There is a bug in the Auctioneer (timed auction) `execute_sale` method, where no `remaining_accounts` are passed forward in the CPI  to AuctionHouse – but AuctionHouse expects `remaining_accounts` to be passed to pay creators.

Specifically: The `execute_sale` function CPI's into the` auctioneer_execute_sale` function in AuctionHouse. This in turn calls the `auctioneer_execute_sale_logic` function which calls the `pay_creator_fees` function. Here,`ctx.remaining_accounts` is passed in as an argument. However, `ctx.remaining_accounts` will always be empty, since the CPI from `execute_sale` (the initial call) never forwards any `remaining_accounts`

This results in an error: `insufficient account keys for instruction`

### Fix
The fix is to "forward" `remaining_accounts` passed by the initial caller into the CPI.

### Tests
Tested in auctioneer with `cargo test`, all tests pass

### Notes
It should be noted in documentation that the `execute_sale` function depends on `remaining_accounts`

### CODE REVIEW

**Comment by blockiosaurus** [comment]
Hey @sohanvichare this looks awesome! Can you install solita (https://www.npmjs.com/package/@metaplex-foundation/solita) and regenerate the SDK by running `solita` in the `auctioneer/js` directory. Alternatively I can submit a PR to your repo that you can merge in, if that's easier for you! Either way thank you for catching this and your first contribution, hopefully of many!

**Comment by sohanvichare** [comment]
> Hey @sohanvichare this looks awesome! Can you install solita (https://www.npmjs.com/package/@metaplex-foundation/solita) and regenerate the SDK by running `solita` in the `auctioneer/js` directory. Alternatively I can submit a PR to your repo that you can merge in, if that's easier for you! Either way thank you for catching this and your first contribution, hopefully of many!

Thanks @blockiosaurus – just regenerated the SDK, thanks for pointing me towards that. I hope so too! :D

**Comment by sohanvichare** [comment]
> Verify package library / verify-package-library

@blockiosaurus I regenerated by installing `solita` globally and then running it in the `js` directory of auctioneer, but it looks like `Verify package library` task is still failing, I'm not sure why.  

I noticed in the Details section of the task it says that anchor v0.22 is being used, whereas I'm on the latest one (0.24) locally, could that be the issue?
```
env:
    NODE_VERSION: 17.0.1
    ANCHOR_VERSION: 0.22.0
    SOLANA_VERSION_STABLE: 1.9.22
    RUST_TOOLCHAIN: stable
    RUSTC_HASH: a83[14](https://github.com/metaplex-foundation/metaplex-program-library/runs/7221911862?check_suite_focus=true#step:7:14)ef7d
```

**Comment by sohanvichare** [comment]
> > Verify package library / verify-package-library
> 
> @blockiosaurus I regenerated by installing `solita` globally and then running it in the `js` directory of auctioneer, but it looks like `Verify package library` task is still failing, I'm not sure why.
> 
> I noticed in the Details section of the task it says that anchor v0.22 is being used, whereas I'm on the latest one (0.24) locally, could that be the issue?
> 
> ```
> env:
>     NODE_VERSION: 17.0.1
>     ANCHOR_VERSION: 0.22.0
>     SOLANA_VERSION_STABLE: 1.9.22
>     RUST_TOOLCHAIN: stable
>     RUSTC_HASH: a83[14](https://github.com/metaplex-foundation/metaplex-program-library/runs/7221911862?check_suite_focus=true#step:7:14)ef7d
> ```

Hey, @blockiosaurus, wanted to bump on this. Anything I can do to get this fixed?

**Comment by jshiohaha** [comment]
> > Verify package library / verify-package-library
> 
> @blockiosaurus I regenerated by installing `solita` globally and then running it in the `js` directory of auctioneer, but it looks like `Verify package library` task is still failing, I'm not sure why.
> 
> I noticed in the Details section of the task it says that anchor v0.22 is being used, whereas I'm on the latest one (0.24) locally, could that be the issue?
> 
> ```
> env:
>     NODE_VERSION: 17.0.1
>     ANCHOR_VERSION: 0.22.0
>     SOLANA_VERSION_STABLE: 1.9.22
>     RUST_TOOLCHAIN: stable
>     RUSTC_HASH: a83[14](https://github.com/metaplex-foundation/metaplex-program-library/runs/7221911862?check_suite_focus=true#step:7:14)ef7d
> ```

hey @sohanvichare 👋🏼 just hopping in since i added that `Verify package library` workflow. It's a little misleading but the Anchor version you're referencing is a left-over environment variable. We actually use something called rustbin to find and install the local version of anchor. See build logs below ⬇️ 
```
>> generate library
2022-07-06T19:57:20.231Z solita:info Found '.prettierrc.js' in current directory and using that to format code
2022-07-06T19:57:20.245Z rustbin:info Cannot access /home/runner/work/metaplex-program-library/metaplex-program-library/auctioneer/js/.crates/bin/anchor thus will need to install the first time
2022-07-06T19:57:20.246Z rustbin:info Type  Name         Version
----  ----         -------
lib   anchor-lang  ~0.24.2
bin   anchor       <unknown
2022-07-06T19:57:20.246Z solita:info No existing version found for anchor.
2022-07-06T19:57:20.246Z solita:info Will install version matching "anchor-lang: '~0.24.2'" to /home/runner/work/metaplex-program-library/metaplex-program-library/auctioneer/js/.crates/bin/anchor
2022-07-06T19:57:20.246Z rustbin:info Installing ~0.24.2 compatible version of anchor
2022-07-06T19:57:20.247Z rustbin:info cargo install anchor-cli --version ~0.24.2 --force --root /home/runner/work/metaplex-program-library/metaplex-program-library/auctioneer/js/.crates
    Updating crates.io index
 Downloading crates ...
  Downloaded anchor-cli v0.24.2
  Installing anchor-cli v0.24.2
```

Out of curiosity, I cloned your repo and ran `yarn api:gen` on this branch just to check the diff. It looks like there might have been an update to solita behind the scenes (see published package here: https://www.npmjs.com/package/@metaplex-foundation/solita). Based on the diff + pull request history from the solita repo (https://github.com/metaplex-foundation/solita/pull/63), it looks like the main diff might be from a recent change.

```
diff --git a/auctioneer/js/src/generated/accounts/AuctioneerAuthority.ts b/auctioneer/js/src/generated/accounts/AuctioneerAuthority.ts
index a445ea2..faab9e0 100644
--- a/auctioneer/js/src/generated/accounts/AuctioneerAuthority.ts
+++ b/auctioneer/js/src/generated/accounts/AuctioneerAuthority.ts
@@ -7,7 +7,6 @@

 import * as beet from '@metaplex-foundation/beet';
 import * as web3 from '@solana/web3.js';
-import * as beetSolana from '@metaplex-foundation/beet-solana';

 /**
  * Arguments used to create {@link AuctioneerAuthority}
@@ -18,7 +17,7 @@ export type AuctioneerAuthorityArgs = {
   bump: number;
 };

-export const auctioneerAuthorityDiscriminator = [228, 74, 255, 245, 96, 83, 197, 12];
+const auctioneerAuthorityDiscriminator = [228, 74, 255, 245, 96, 83, 197, 12];
 /**
  * Holds the data for the {@link AuctioneerAuthority} Account and provides de/serialization
  * functionality for that data
@@ -64,18 +63,6 @@ export class AuctioneerAuthority implements AuctioneerAuthorityArgs {
     return AuctioneerAuthority.fromAccountInfo(accountInfo, 0)[0];
   }

-  /**
-   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
-   * to fetch accounts matching filters that can be specified via that builder.
-   *
-   * @param programId - the program that owns the accounts we are filtering
-   */
-  static gpaBuilder(
-    programId: web3.PublicKey = new web3.PublicKey('neer8g6yJq2mQM6KbnViEDAD4gr3gRZyMMf4F2p3MEh'),
-  ) {
-    return beetSolana.GpaBuilder.fromStruct(programId, auctioneerAuthorityBeet);
-  }
-
   /**
    * Deserializes the {@link AuctioneerAuthority} from the provided data Buffer.
    * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
    *
```

FWIW, I regenerated the SDK (`yarn api:gen`), committed those changes (`git commit src && git commit -m "gen api"`), and then regenerated the SDK (`yarn api:gen && git status`) for an empty output. This means the `Verify package library` would pass ✅

**Comment by sohanvichare** [comment]
> > > Verify package library / verify-package-library
> > 
> > 
> > @blockiosaurus I regenerated by installing `solita` globally and then running it in the `js` directory of auctioneer, but it looks like `Verify package library` task is still failing, I'm not sure why.
> > I noticed in the Details section of the task it says that anchor v0.22 is being used, whereas I'm on the latest one (0.24) locally, could that be the issue?
> > ```
> > env:
> >     NODE_VERSION: 17.0.1
> >     ANCHOR_VERSION: 0.22.0
> >     SOLANA_VERSION_STABLE: 1.9.22
> >     RUST_TOOLCHAIN: stable
> >     RUSTC_HASH: a83[14](https://github.com/metaplex-foundation/metaplex-program-library/runs/7221911862?check_suite_focus=true#step:7:14)ef7d
> > ```
> 
> hey @sohanvichare 👋🏼 hopping in since i added that `Verify package library` workflow. It's a little misleading but the Anchor version you're referencing is a left-over environment variable. We actually use something called rustbin to find and install the local version of anchor. This means we are using Anchor v0.24.2 - see build logs below ⬇️
> 
> ```
> >> generate library
> 2022-07-06T19:57:20.231Z solita:info Found '.prettierrc.js' in current directory and using that to format code
> 2022-07-06T19:57:20.245Z rustbin:info Cannot access /home/runner/work/metaplex-program-library/metaplex-program-library/auctioneer/js/.crates/bin/anchor thus will need to install the first time
> 2022-07-06T19:57:20.246Z rustbin:info Type  Name         Version
> ----  ----         -------
> lib   anchor-lang  ~0.24.2
> bin   anchor       <unknown
> 2022-07-06T19:57:20.246Z solita:info No existing version found for anchor.
> 2022-07-06T19:57:20.246Z solita:info Will install version matching "anchor-lang: '~0.24.2'" to /home/runner/work/metaplex-program-library/metaplex-program-library/auctioneer/js/.crates/bin/anchor
> 2022-07-06T19:57:20.246Z rustbin:info Installing ~0.24.2 compatible version of anchor
> 2022-07-06T19:57:20.247Z rustbin:info cargo install anchor-cli --version ~0.24.2 --force --root /home/runner/work/metaplex-program-library/metaplex-program-library/auctioneer/js/.crates
>     Updating crates.io index
>  Downloading crates ...
>   Downloaded anchor-cli v0.24.2
>   Installing anchor-cli v0.24.2
> ```
> 
> Out of curiosity, I cloned your repo and ran `yarn api:gen` on this branch just to check the diff. It looks like there might have been an update to solita behind the scenes (see published package here: https://www.npmjs.com/package/@metaplex-foundation/solita). Based on the diff + pull request history from the solita repo ([metaplex-foundation/solita#63](https://github.com/metaplex-foundation/solita/pull/63)), it looks like the main diff might be from a recent change.
> 
> ```
> diff --git a/auctioneer/js/src/generated/accounts/AuctioneerAuthority.ts b/auctioneer/js/src/generated/accounts/AuctioneerAuthority.ts
> index a445ea2..faab9e0 100644
> --- a/auctioneer/js/src/generated/accounts/AuctioneerAuthority.ts
> +++ b/auctioneer/js/src/generated/accounts/AuctioneerAuthority.ts
> @@ -7,7 +7,6 @@
> 
>  import * as beet from '@metaplex-foundation/beet';
>  import * as web3 from '@solana/web3.js';
> -import * as beetSolana from '@metaplex-foundation/beet-solana';
> 
>  /**
>   * Arguments used to create {@link AuctioneerAuthority}
> @@ -18,7 +17,7 @@ export type AuctioneerAuthorityArgs = {
>    bump: number;
>  };
> 
> -export const auctioneerAuthorityDiscriminator = [228, 74, 255, 245, 96, 83, 197, 12];
> +const auctioneerAuthorityDiscriminator = [228, 74, 255, 245, 96, 83, 197, 12];
>  /**
>   * Holds the data for the {@link AuctioneerAuthority} Account and provides de/serialization
>   * functionality for that data
> @@ -64,18 +63,6 @@ export class AuctioneerAuthority implements AuctioneerAuthorityArgs {
>      return AuctioneerAuthority.fromAccountInfo(accountInfo, 0)[0];
>    }
> 
> -  /**
> -   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
> -   * to fetch accounts matching filters that can be specified via that builder.
> -   *
> -   * @param programId - the program that owns the accounts we are filtering
> -   */
> -  static gpaBuilder(
> -    programId: web3.PublicKey = new web3.PublicKey('neer8g6yJq2mQM6KbnViEDAD4gr3gRZyMMf4F2p3MEh'),
> -  ) {
> -    return beetSolana.GpaBuilder.fromStruct(programId, auctioneerAuthorityBeet);
> -  }
> -
>    /**
>     * Deserializes the {@link AuctioneerAuthority} from the provided data Buffer.
>     * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
>     *
> ```
> 
> FWIW, I regenerated the SDK (`yarn api:gen`), committed those changes (`git commit src && git commit -m "gen api"`), and then regenerated the SDK (`yarn api:gen && git status`) for an empty output. This means the `Verify package library` would pass ✅

Thank you @jshiohaha! Got it, new solita version makes sense. Just used `yarn api:gen`, and `yarn api:gen && git status` is giving me an empty output. Excited to get this merged.

**Comment by skulltv** [comment]
@blockiosaurus @jshiohaha Want to quickly bump this, could someone run checks? Thanks for bearing with me while I  figure this verify-package thing out 😂😂😂, it will be much faster next time

**Comment by sohanvichare** [comment]
@blockiosaurus @jshiohaha want to quickly bump this – can someone run checks? Thanks for bearing with me while I figure this verify-package thing out 😂😂😂, it'll be much faster next time

**Comment by blockiosaurus** [comment]
Thanks for the bump. @jshiohaha can you take a look at why the test is still failing or submit a PR against their fork that'll help it pass? I'd love to get this in this week.

**Comment by blockiosaurus** [comment]
Power merged! Thanks so much for this @sohanvichare! Hopefully the first contribution of many!

**Comment by RashidInvo** [comment]
Hi there! i am working on this flow and i passed remaining accounts and for first time execute_sale is working fine but second time if i list same nft i'm facing error of insufficient accounts can you please check!!!

**Pull request merged**
